#! /bin/sh

# autostart

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
/usr/lib/polkit-kde-authentication-agent-1 &
dunst &
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          23

# colors

bspc config normal_border_color       "#FFFFFF"
bspc config active_border_color       "#FFFFFF"
bspc config focused_border_color      "#06dbd0"
bspc config presel_feedback_color     "#000000"
bspc config urgent_border_color       "#d01104"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a firefox:Navigator desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
